# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .bastion import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "aws-tailscale",
  "mod": "index",
  "fqn": "pulumi_aws_tailscale",
  "classes": {
   "aws-tailscale:index:Bastion": "Bastion"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "aws-tailscale",
  "token": "pulumi:providers:aws-tailscale",
  "fqn": "pulumi_aws_tailscale",
  "class": "Provider"
 }
]
"""
)
