// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.TailscaleBastion.Inputs
{

    /// <summary>
    /// Settings for configuring this node as a peer relay server.
    /// </summary>
    public sealed class PeerRelaySettingsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to enable peer relay functionality.
        /// </summary>
        [Input("enable")]
        public Input<bool>? Enable { get; set; }

        /// <summary>
        /// The port to use for the relay server.
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        public PeerRelaySettingsArgs()
        {
            Enable = false;
            Port = 12345;
        }
        public static new PeerRelaySettingsArgs Empty => new PeerRelaySettingsArgs();
    }
}
