# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: tailscale-bastion
pluginDownloadUrl: "github://api.github.com/lbrlabs"
description: "A Pulumi package for creating a tailscale bastion in AWS."
repository: "https://github.com/lbrlabs/pulumi-tailscale-bastion"
publisher: "lbrlabs"
displayname: "tailscale-bastion"
keywords:
  - aws
  - tailscale
  - lbrlabs
  - kind/component
  - category/network
resources:
  tailscale-bastion:azure:Bastion:
    isComponent: true
    inputProperties:
      enableSSH:
        type: boolean
        description: "Whether to enable SSH access to the bastion."
        default: true
      resourceGroupName:
        type: string
        description: "The Azure resource group to create the bastion in."
      subnetId:
        type: string
        description: "The subnet Ids to launch instances in."
      routes:
        type: array
        items:
          type: string
        description: "The routes you'd like to advertise via tailscale."
      location:
        type: string
        description: "The Azure region you're using."
      instanceSku:
        type: string
        description: "The Azure instance SKU to use for the bastion."
      highAvailability:
        type: boolean
        description: "Whether the bastion should be highly available."
        default: false
      public:
        type: boolean
        description: "Whether the bastion should have a public IP."
        default: false
      tailscaleTags:
        type: array
        items:
          type: string
        description: "The tags to apply to the tailnet device andauth key. This tag should be added to your oauth key and ACL."
    requiredInputs:
      - highAvailability
      - resourceGroupName
      - subnetId
      - routes
      - location
      - tailscaleTags
    properties:
      scaleSetName:
        type: string
        description: "The name of the Scaleset that managed the bastion instances"
      privateKey:
        type: string
        description: "The SSH private key to access your bastion"
    required:
      - scaleSetName
      - privateKey
  tailscale-bastion:aws:Bastion:
    isComponent: true
    inputProperties:
      hostname:
        type: string
        description: "The hostname of the bastion."
      public:
        type: boolean
        description: "Whether the bastion is going in public subnets."
        default: false
      enableSSH:
        type: boolean
        description: "Whether to enable SSH access to the bastion."
        default: true
      enableAppConnector:
        type: boolean
        description: "Whether the bastion advertises itself as an app connector."
        default: false
      enableExitNode:
        type: boolean
        description: "Whether the subnet router can advertise itself as an exit node."
        default: false
      highAvailability:
        type: boolean
        description: "Whether the bastion should be highly available."
        default: false
      vpcId:
        type: string
        description: "The VPC the Bastion should be created in."
      tailscaleTags:
        type: array
        items:
          type: string
        description: "The tags to apply to the tailnet device andauth key. This tag should be added to your oauth key and ACL."
      subnetIds:
        type: array
        items:
          type: string
        description: "The subnet Ids to launch instances in."
      routes:
        type: array
        items:
          type: string
        description: "The routes you'd like to advertise via tailscale."
      region:
        type: string
        description: "The AWS region you're using."
      instanceType:
        type: string
        description: "The EC2 instance type to use for the bastion."
      oauthClientSecret:
        type: string
        description: "An OAuth Client Secret to use for authenticating Tailscale clients."
    requiredInputs:
      - highAvailability
      - vpcId
      - subnetIds
      - region
      - tailscaleTags
    properties:
      asgName:
        type: string
        description: "The name of the ASG that managed the bastion instances"
      privateKey:
        type: string
        description: "The SSH private key to access your bastion"
    required:
      - asgName
      - privateKey
  tailscale-bastion:kubernetes:Bastion:
    isComponent: true
    inputProperties:
      highAvailability:
        type: boolean
        description: "Whether the bastion should be highly available."
        default: false
      tailscaleTags:
        type: array
        items:
          type: string
        description: "The tags to apply to the tailnet device andauth key. This tag should be added to your oauth key and ACL."
      createNamespace:
        type: boolean
        description: "Whether we should create a new namespace."
        plain: true
      namespace:
        "$ref": "/kubernetes/v4.21.1/schema.json#/resources/kubernetes:core%2Fv1:Namespace"
        description: The bucket resource.
      routes:
        type: array
        items:
          type: string
        description: "The routes to advertise to tailscale. This is likely the Pod and Service CIDR."
    requiredInputs:
      - highAvailability
      - createNamespace
      - routes
      - tailscaleTags
    properties:
      deploymentName:
        type: string
        description: "The name of the kubernetes deployment that contains the tailscale bastion"
    required:
      - deploymentName
language:
  csharp:
    packageReferences:
      Pulumi: 3.*
      Pulumi.Aws: 6.*
      Pulumi.Azure: 6.*
      Pulumi.Kubernetes: 4.*
      Pulumi.Tls: 4.*
      Pulumi.Tailscale: 0.*
    rootNamespace: "Lbrlabs.PulumiPackage"
  go:
    generateResourceContainerTypes: true
    importBasePath: github.com/lbrlabs/pulumi-tailscale-bastion/sdk/go/bastion
  nodejs:
    dependencies:
      "@pulumi/aws": "^6.0.0"
      "@pulumi/azure": "^6.0.0"
      "@pulumi/tls": "^4.0.0"
      "@pulumi/kubernetes": "^4.0.0"
      "@pulumi/tailscale": "^0.18.0"
    devDependencies:
      typescript: "^3.7.0"
      glob: "^9.0.0"
      minimatch: "^5.0.0"
    packageName: "@lbrlabs/pulumi-tailscalebastion"
  python:
    packageName: "lbrlabs_pulumi_tailscalebastion"
    requires:
      pulumi: ">=3.0.0,<4.0.0"
      pulumi-kubernetes: ">=4.0.0,<5.0.0"
      pulumi-aws: ">=6.0.0,<7.0.0"
      pulumi-azure: ">=6.0.0,<7.0.0"
      pulumi-tls: ">=4.0.0,<5.0.0"
      pulumi-tailscale: ">=0.0.0,<1.0.0"
