// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.TailscaleBastion.Gcp
{
    [TailscaleBastionResourceType("tailscale-bastion:gcp:Bastion")]
    public partial class Bastion : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The name of the autoscaler that manages the instances.
        /// </summary>
        [Output("autoscalerName")]
        public Output<string> AutoscalerName { get; private set; } = null!;

        /// <summary>
        /// The name of the group manager that manages the instances.
        /// </summary>
        [Output("groupManagerName")]
        public Output<string> GroupManagerName { get; private set; } = null!;

        /// <summary>
        /// The SSH private key to access your bastion.
        /// </summary>
        [Output("privateKey")]
        public Output<string> PrivateKey { get; private set; } = null!;

        /// <summary>
        /// The name of the target that manages the instances.
        /// </summary>
        [Output("targetPoolName")]
        public Output<string> TargetPoolName { get; private set; } = null!;


        /// <summary>
        /// Create a Bastion resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bastion(string name, BastionArgs args, ComponentResourceOptions? options = null)
            : base("tailscale-bastion:gcp:Bastion", name, args ?? new BastionArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class BastionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The GCP machine type to launch. Defaults to f1-micro.
        /// </summary>
        [Input("machineType")]
        public Input<string>? MachineType { get; set; }

        /// <summary>
        /// The route you'd like to advertise via tailscale.
        /// </summary>
        [Input("route", required: true)]
        public Input<string> Route { get; set; } = null!;

        /// <summary>
        /// The subnetwork to create the bastion in.
        /// </summary>
        [Input("subnetNetworkId", required: true)]
        public Input<string> SubnetNetworkId { get; set; } = null!;

        public BastionArgs()
        {
        }
        public static new BastionArgs Empty => new BastionArgs();
    }
}
