// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.TailscaleBastion.Azure
{
    [TailscaleBastionResourceType("tailscale-bastion:azure:Bastion")]
    public partial class Bastion : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The SSH private key to access your bastion
        /// </summary>
        [Output("privateKey")]
        public Output<string> PrivateKey { get; private set; } = null!;

        /// <summary>
        /// The name of the Scaleset that managed the bastion instances
        /// </summary>
        [Output("scaleSetName")]
        public Output<string> ScaleSetName { get; private set; } = null!;


        /// <summary>
        /// Create a Bastion resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bastion(string name, BastionArgs args, ComponentResourceOptions? options = null)
            : base("tailscale-bastion:azure:Bastion", name, args ?? new BastionArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class BastionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to enable SSH access to the bastion.
        /// </summary>
        [Input("enableSSH")]
        public Input<bool>? EnableSSH { get; set; }

        /// <summary>
        /// Whether the bastion should be highly available.
        /// </summary>
        [Input("highAvailability", required: true)]
        public Input<bool> HighAvailability { get; set; } = null!;

        /// <summary>
        /// The Azure instance SKU to use for the bastion.
        /// </summary>
        [Input("instanceSku")]
        public Input<string>? InstanceSku { get; set; }

        /// <summary>
        /// The Azure region you're using.
        /// </summary>
        [Input("location", required: true)]
        public Input<string> Location { get; set; } = null!;

        /// <summary>
        /// Whether the bastion should have a public IP.
        /// </summary>
        [Input("public")]
        public Input<bool>? Public { get; set; }

        /// <summary>
        /// The Azure resource group to create the bastion in.
        /// </summary>
        [Input("resourceGroupName", required: true)]
        public Input<string> ResourceGroupName { get; set; } = null!;

        [Input("routes", required: true)]
        private InputList<string>? _routes;

        /// <summary>
        /// The routes you'd like to advertise via tailscale.
        /// </summary>
        public InputList<string> Routes
        {
            get => _routes ?? (_routes = new InputList<string>());
            set => _routes = value;
        }

        /// <summary>
        /// The subnet Ids to launch instances in.
        /// </summary>
        [Input("subnetId", required: true)]
        public Input<string> SubnetId { get; set; } = null!;

        [Input("tailscaleTags", required: true)]
        private InputList<string>? _tailscaleTags;

        /// <summary>
        /// The tags to apply to the tailnet device andauth key. This tag should be added to your oauth key and ACL.
        /// </summary>
        public InputList<string> TailscaleTags
        {
            get => _tailscaleTags ?? (_tailscaleTags = new InputList<string>());
            set => _tailscaleTags = value;
        }

        public BastionArgs()
        {
            EnableSSH = true;
            HighAvailability = false;
            Public = false;
        }
        public static new BastionArgs Empty => new BastionArgs();
    }
}
