// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { BastionArgs } from "./bastion";
export type Bastion = import("./bastion").Bastion;
export const Bastion: typeof import("./bastion").Bastion = null as any;
utilities.lazyLoad(exports, ["Bastion"], () => require("./bastion"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "tailscale-bastion:kubernetes:Bastion":
                return new Bastion(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("tailscale-bastion", "kubernetes", _module)
