// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.TailscaleBastion.Kubernetes
{
    [TailscaleBastionResourceType("tailscale-bastion:kubernetes:Bastion")]
    public partial class Bastion : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// The name of the kubernetes deployment that contains the tailscale bastion
        /// </summary>
        [Output("deploymentName")]
        public Output<string> DeploymentName { get; private set; } = null!;


        /// <summary>
        /// Create a Bastion resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Bastion(string name, BastionArgs args, ComponentResourceOptions? options = null)
            : base("tailscale-bastion:kubernetes:Bastion", name, args ?? new BastionArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/lbrlabs",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class BastionArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether we should create a new namespace.
        /// </summary>
        [Input("createNamespace", required: true)]
        public bool CreateNamespace { get; set; }

        /// <summary>
        /// The bucket resource.
        /// </summary>
        [Input("namespace")]
        public Input<Pulumi.Kubernetes.Core.V1.Namespace>? Namespace { get; set; }

        [Input("routes", required: true)]
        private InputList<string>? _routes;

        /// <summary>
        /// The routes to advertise to tailscale. This is likely the Pod and Service CIDR.
        /// </summary>
        public InputList<string> Routes
        {
            get => _routes ?? (_routes = new InputList<string>());
            set => _routes = value;
        }

        [Input("tailscaleTags")]
        private InputList<string>? _tailscaleTags;

        /// <summary>
        /// The tags to apply to the tailnet device andauth key. This tag should be added to your oauth key and ACL.
        /// </summary>
        public InputList<string> TailscaleTags
        {
            get => _tailscaleTags ?? (_tailscaleTags = new InputList<string>());
            set => _tailscaleTags = value;
        }

        public BastionArgs()
        {
        }
        public static new BastionArgs Empty => new BastionArgs();
    }
}
