// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

import * as utilities from "../utilities";

/**
 * Settings for configuring this node as a peer relay server.
 */
export interface PeerRelaySettingsArgs {
    /**
     * Whether to enable peer relay functionality.
     */
    enable?: pulumi.Input<boolean>;
    /**
     * The port to use for the relay server.
     */
    port?: pulumi.Input<number>;
}
/**
 * peerRelaySettingsArgsProvideDefaults sets the appropriate defaults for PeerRelaySettingsArgs
 */
export function peerRelaySettingsArgsProvideDefaults(val: PeerRelaySettingsArgs): PeerRelaySettingsArgs {
    return {
        ...val,
        enable: (val.enable) ?? false,
        port: (val.port) ?? 12345,
    };
}
