// Code generated by Pulumi SDK Generator DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bastion

import (
	"context"
	"reflect"

	"github.com/lbrlabs/pulumi-tailscale-bastion/sdk/go/bastion/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

// Settings for configuring this node as a peer relay server.
type PeerRelaySettings struct {
	// Whether to enable peer relay functionality.
	Enable *bool `pulumi:"enable"`
	// The port to use for the relay server.
	Port *int `pulumi:"port"`
}

// Defaults sets the appropriate defaults for PeerRelaySettings
func (val *PeerRelaySettings) Defaults() *PeerRelaySettings {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Enable == nil {
		enable_ := false
		tmp.Enable = &enable_
	}
	if tmp.Port == nil {
		port_ := 12345
		tmp.Port = &port_
	}
	return &tmp
}

// PeerRelaySettingsInput is an input type that accepts PeerRelaySettingsArgs and PeerRelaySettingsOutput values.
// You can construct a concrete instance of `PeerRelaySettingsInput` via:
//
//	PeerRelaySettingsArgs{...}
type PeerRelaySettingsInput interface {
	pulumi.Input

	ToPeerRelaySettingsOutput() PeerRelaySettingsOutput
	ToPeerRelaySettingsOutputWithContext(context.Context) PeerRelaySettingsOutput
}

// Settings for configuring this node as a peer relay server.
type PeerRelaySettingsArgs struct {
	// Whether to enable peer relay functionality.
	Enable pulumi.BoolPtrInput `pulumi:"enable"`
	// The port to use for the relay server.
	Port pulumi.IntPtrInput `pulumi:"port"`
}

// Defaults sets the appropriate defaults for PeerRelaySettingsArgs
func (val *PeerRelaySettingsArgs) Defaults() *PeerRelaySettingsArgs {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Enable == nil {
		tmp.Enable = pulumi.BoolPtr(false)
	}
	if tmp.Port == nil {
		tmp.Port = pulumi.IntPtr(12345)
	}
	return &tmp
}
func (PeerRelaySettingsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*PeerRelaySettings)(nil)).Elem()
}

func (i PeerRelaySettingsArgs) ToPeerRelaySettingsOutput() PeerRelaySettingsOutput {
	return i.ToPeerRelaySettingsOutputWithContext(context.Background())
}

func (i PeerRelaySettingsArgs) ToPeerRelaySettingsOutputWithContext(ctx context.Context) PeerRelaySettingsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeerRelaySettingsOutput)
}

func (i PeerRelaySettingsArgs) ToPeerRelaySettingsPtrOutput() PeerRelaySettingsPtrOutput {
	return i.ToPeerRelaySettingsPtrOutputWithContext(context.Background())
}

func (i PeerRelaySettingsArgs) ToPeerRelaySettingsPtrOutputWithContext(ctx context.Context) PeerRelaySettingsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeerRelaySettingsOutput).ToPeerRelaySettingsPtrOutputWithContext(ctx)
}

// PeerRelaySettingsPtrInput is an input type that accepts PeerRelaySettingsArgs, PeerRelaySettingsPtr and PeerRelaySettingsPtrOutput values.
// You can construct a concrete instance of `PeerRelaySettingsPtrInput` via:
//
//	        PeerRelaySettingsArgs{...}
//
//	or:
//
//	        nil
type PeerRelaySettingsPtrInput interface {
	pulumi.Input

	ToPeerRelaySettingsPtrOutput() PeerRelaySettingsPtrOutput
	ToPeerRelaySettingsPtrOutputWithContext(context.Context) PeerRelaySettingsPtrOutput
}

type peerRelaySettingsPtrType PeerRelaySettingsArgs

func PeerRelaySettingsPtr(v *PeerRelaySettingsArgs) PeerRelaySettingsPtrInput {
	return (*peerRelaySettingsPtrType)(v)
}

func (*peerRelaySettingsPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**PeerRelaySettings)(nil)).Elem()
}

func (i *peerRelaySettingsPtrType) ToPeerRelaySettingsPtrOutput() PeerRelaySettingsPtrOutput {
	return i.ToPeerRelaySettingsPtrOutputWithContext(context.Background())
}

func (i *peerRelaySettingsPtrType) ToPeerRelaySettingsPtrOutputWithContext(ctx context.Context) PeerRelaySettingsPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PeerRelaySettingsPtrOutput)
}

// Settings for configuring this node as a peer relay server.
type PeerRelaySettingsOutput struct{ *pulumi.OutputState }

func (PeerRelaySettingsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*PeerRelaySettings)(nil)).Elem()
}

func (o PeerRelaySettingsOutput) ToPeerRelaySettingsOutput() PeerRelaySettingsOutput {
	return o
}

func (o PeerRelaySettingsOutput) ToPeerRelaySettingsOutputWithContext(ctx context.Context) PeerRelaySettingsOutput {
	return o
}

func (o PeerRelaySettingsOutput) ToPeerRelaySettingsPtrOutput() PeerRelaySettingsPtrOutput {
	return o.ToPeerRelaySettingsPtrOutputWithContext(context.Background())
}

func (o PeerRelaySettingsOutput) ToPeerRelaySettingsPtrOutputWithContext(ctx context.Context) PeerRelaySettingsPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v PeerRelaySettings) *PeerRelaySettings {
		return &v
	}).(PeerRelaySettingsPtrOutput)
}

// Whether to enable peer relay functionality.
func (o PeerRelaySettingsOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v PeerRelaySettings) *bool { return v.Enable }).(pulumi.BoolPtrOutput)
}

// The port to use for the relay server.
func (o PeerRelaySettingsOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v PeerRelaySettings) *int { return v.Port }).(pulumi.IntPtrOutput)
}

type PeerRelaySettingsPtrOutput struct{ *pulumi.OutputState }

func (PeerRelaySettingsPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**PeerRelaySettings)(nil)).Elem()
}

func (o PeerRelaySettingsPtrOutput) ToPeerRelaySettingsPtrOutput() PeerRelaySettingsPtrOutput {
	return o
}

func (o PeerRelaySettingsPtrOutput) ToPeerRelaySettingsPtrOutputWithContext(ctx context.Context) PeerRelaySettingsPtrOutput {
	return o
}

func (o PeerRelaySettingsPtrOutput) Elem() PeerRelaySettingsOutput {
	return o.ApplyT(func(v *PeerRelaySettings) PeerRelaySettings {
		if v != nil {
			return *v
		}
		var ret PeerRelaySettings
		return ret
	}).(PeerRelaySettingsOutput)
}

// Whether to enable peer relay functionality.
func (o PeerRelaySettingsPtrOutput) Enable() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *PeerRelaySettings) *bool {
		if v == nil {
			return nil
		}
		return v.Enable
	}).(pulumi.BoolPtrOutput)
}

// The port to use for the relay server.
func (o PeerRelaySettingsPtrOutput) Port() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *PeerRelaySettings) *int {
		if v == nil {
			return nil
		}
		return v.Port
	}).(pulumi.IntPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PeerRelaySettingsInput)(nil)).Elem(), PeerRelaySettingsArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*PeerRelaySettingsPtrInput)(nil)).Elem(), PeerRelaySettingsArgs{})
	pulumi.RegisterOutputType(PeerRelaySettingsOutput{})
	pulumi.RegisterOutputType(PeerRelaySettingsPtrOutput{})
}
